
import React, { useState } from 'react';
import { ProjectData } from '../types';
import { Button, Card, SectionTitle } from './Shared';
import { FileText, Download, Copy, Check, EyeOff, Eye } from 'lucide-react';
import { authService } from '../services/authService';

interface StepReportProps {
  data: ProjectData;
}

export const StepReport: React.FC<StepReportProps> = ({ data }) => {
  const [copied, setCopied] = useState(false);
  const [whiteLabel, setWhiteLabel] = useState(false);
  const [agencyName, setAgencyName] = useState('My Agency');
  
  const user = authService.getCurrentUser();
  const isAgency = user?.subscription === 'agency';

  const generateMarkdown = () => {
    const header = whiteLabel 
      ? `# Marketing Strategy Report: ${data.productName}\nPrepared by: ${agencyName}` 
      : `# Marketing Strategy Report: ${data.productName}\nGenerated by Meti Marketing Engine`;

    return `
${header}

## 1. Product Summary
${data.productDescription}

## 2. Target Niche
**Niche:** ${data.selectedNiche?.name || 'Not Selected'}
**Score:** ${data.selectedNiche?.profitabilityScore || 0}/100
**Reasoning:** ${data.selectedNiche?.reasoning || 'N/A'}

## 3. Ideal Customer Persona
**Role:** ${data.persona?.jobTitle || 'N/A'}
**Age:** ${data.persona?.ageRange || 'N/A'}
**Pain Points:**
${data.persona?.painPoints?.map(p => `- ${p}`).join('\n') || 'N/A'}
**Buying Triggers:**
${data.persona?.buyingTriggers?.map(t => `- ${t}`).join('\n') || 'N/A'}

## 4. Lead Magnets
${data.generatedMagnets?.map(m => `### ${m.title} (${m.type})
Hook: ${m.hook}
${m.contentDraft ? `\n*Draft Content Available in App*` : ''}
`).join('\n') || 'None Generated'}

## 5. Sales Qualification (BANT)
${data.qualificationFramework?.map((q, i) => `${i+1}. ${q.question}
   (Intent: ${q.intent})`).join('\n') || 'None Generated'}

## 6. Landing Page Copy
**Headline:** ${data.landingPage?.headline || 'N/A'}
**Subhead:** ${data.landingPage?.subheadline || 'N/A'}
**CTA:** ${data.landingPage?.ctaPrimary || 'N/A'}
`;
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generateMarkdown());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const element = document.createElement("a");
    const file = new Blob([generateMarkdown()], {type: 'text/markdown'});
    element.href = URL.createObjectURL(file);
    element.download = `${data.productName.replace(/\s+/g, '_')}_Strategy.md`;
    document.body.appendChild(element);
    element.click();
  };

  return (
    <div className="max-w-4xl mx-auto animate-fadeIn">
      <SectionTitle title="Strategy Report" subtitle="Your comprehensive marketing master plan." />

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
        <div className="flex flex-col gap-6">
          <Card className="flex flex-col items-center text-center p-8 bg-gradient-to-br from-indigo-900/20 to-slate-900 h-full justify-center">
            <FileText size={48} className="text-indigo-400 mb-4" />
            <h3 className="text-xl font-bold text-white mb-2">Strategy Complete</h3>
            <p className="text-slate-400 mb-6">
              Your end-to-end marketing strategy is ready. It includes niche analysis, persona deep-dives, lead magnets, and sales scripts.
            </p>
            <div className="flex gap-4 w-full">
              <Button onClick={handleCopy} variant="secondary" className="flex-1">
                {copied ? <Check size={18} /> : <Copy size={18} />} Copy Text
              </Button>
              <Button onClick={handleDownload} className="flex-1">
                <Download size={18} /> Download MD
              </Button>
            </div>
          </Card>

          {/* Agency White-label Controls */}
          <div className="bg-slate-800 rounded-lg p-6 border border-slate-700">
             <div className="flex justify-between items-start mb-4">
               <div>
                 <h4 className="text-white font-bold flex items-center gap-2">White-label Options</h4>
                 <p className="text-xs text-slate-400">Remove Meti branding from exports</p>
               </div>
               {isAgency ? (
                 <button 
                   onClick={() => setWhiteLabel(!whiteLabel)}
                   className={`p-1.5 rounded-lg transition-colors ${whiteLabel ? 'bg-indigo-600 text-white' : 'bg-slate-700 text-slate-400'}`}
                 >
                   {whiteLabel ? <EyeOff size={18} /> : <Eye size={18} />}
                 </button>
               ) : (
                 <span className="text-[10px] bg-slate-700 text-slate-400 px-2 py-1 rounded">AGENCY ONLY</span>
               )}
             </div>
             
             {isAgency && whiteLabel && (
               <div className="animate-fadeIn">
                 <label className="text-xs text-slate-400 block mb-1">Agency Name for Report Header</label>
                 <input 
                   type="text" 
                   value={agencyName}
                   onChange={(e) => setAgencyName(e.target.value)}
                   className="w-full bg-slate-900 border border-slate-600 rounded px-3 py-2 text-sm text-white focus:border-indigo-500 outline-none"
                 />
               </div>
             )}
          </div>
        </div>

        <div className="space-y-4">
          <div className="flex items-center justify-between p-4 bg-slate-800 rounded-lg border border-slate-700">
            <span className="text-slate-300">Niche Analysis</span>
            <span className={`text-sm flex items-center gap-1 font-medium ${data.selectedNiche ? 'text-emerald-400' : 'text-slate-500'}`}>
              {data.selectedNiche ? <><Check size={14}/> Complete</> : 'Pending'}
            </span>
          </div>
          <div className="flex items-center justify-between p-4 bg-slate-800 rounded-lg border border-slate-700">
            <span className="text-slate-300">Persona Profile</span>
             <span className={`text-sm flex items-center gap-1 font-medium ${data.persona ? 'text-emerald-400' : 'text-slate-500'}`}>
               {data.persona ? <><Check size={14}/> Complete</> : 'Pending'}
            </span>
          </div>
          <div className="flex items-center justify-between p-4 bg-slate-800 rounded-lg border border-slate-700">
            <span className="text-slate-300">Lead Magnets</span>
            <span className={`font-medium text-sm flex items-center gap-1 ${data.generatedMagnets && data.generatedMagnets.length > 0 ? 'text-emerald-400' : 'text-slate-500'}`}>
              {data.generatedMagnets && data.generatedMagnets.length > 0 ? <><Check size={14}/> {data.generatedMagnets.length} Generated</> : 'Pending'}
            </span>
          </div>
          <div className="flex items-center justify-between p-4 bg-slate-800 rounded-lg border border-slate-700">
            <span className="text-slate-300">Landing Page</span>
             <span className={`font-medium text-sm flex items-center gap-1 ${data.landingPage ? 'text-emerald-400' : 'text-slate-500'}`}>
              {data.landingPage ? <><Check size={14}/> Ready</> : 'Not Generated'}
            </span>
          </div>
        </div>
      </div>
    </div>
  );
};
